// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
// Prefer the common ANON key name; fall back to PUBLISHABLE_KEY for compatibility.
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY ?? import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// In development, print the resolved Supabase env values to the browser console
if (import.meta.env.DEV) {
  const maskedKey = SUPABASE_PUBLISHABLE_KEY
    ? `${String(SUPABASE_PUBLISHABLE_KEY).slice(0, 8)}...${String(SUPABASE_PUBLISHABLE_KEY).slice(-8)}`
    : undefined;
  // eslint-disable-next-line no-console
  console.log('Resolved Supabase env:', { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY: maskedKey });
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});